server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shigongpeng1/microservicecloud-config.git  #Github上面git仓库名称
          username: shigongpeng1
          password: 5211314gpswho