spring:
  application:
    name: eureka7001.com
server:
  port: 7001
eureka:
#  server:             eurake自我保护机制
#    enable-self-preservation: false
  instance:
    hostname: eureka7001.com #eureka服务端的实例名
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    单机 #设置与eureka server交互的地址查询服务于注册服务
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  server:
      peer-node-read-timeout-ms: 200000